### PR TITLE
Bug Fix: Done button fixed position in Add Task modal

### PR DESCRIPTION
**Pull request by bahadirtrkalioglu**
Hello, I have seen your issue and I wanted to solve this bug. Now "Done" named ElevatedButton won't scroll down with the list.

### CODE REVIEW

**Review by Spyy004 — CHANGES_REQUESTED** [review]
This looks good to me.  Can you please take a pull of the latest code, update the Elevated button to the Neopop button in your code and update the PR I think I pushed the Neopop button change when you were working on this change hence you have an elevated button in your code.

**Comment by bahadirtrkalioglu** [comment]
I see, When I working on it there is no Neopop. Okey no problem I am solving it

**Comment by bahadirtrkalioglu** [comment]
Could you review it, is there any problem?

**Review by Spyy004 — APPROVED** [review]
Yeah now looks good

**Pull request merged**
