### PR TITLE
Issue#21-Subramanian the navigation stack from profile to bucket list is odd

### PR DESCRIPTION
**Pull request by subramanian42**
- [x] Ensure that your contribution is relevant to the goals and scope of the project.

- [x] Make sure your changes do not introduce new bugs and pass all existing tests.

- [x] Keep your code clean, well-organized, and documented.

- [x] Provide clear and comprehensive commit messages.

- [ ] Include relevant documentation updates if applicable.

- [x] Be respectful and considerate in your interactions with other contributors.

PR for #21

### CODE REVIEW

**Comment by Spyy004** [comment]
I think you have not taken pull of the latest code. I have made changes in the navigation and implemented a bottom navigation bar. Take a pull of the most updated code and make your navigation changes in that code and update your PR please

**Comment by subramanian42** [comment]
ok

**Comment by Spyy004** [comment]
Do you have the latest code of main with bottombarservice? And did you make a change in the custom_bottom_bar  file to modify the navigaiton logic?

**Comment by subramanian42** [comment]
i have made the required changes

**Comment by Spyy004** [comment]
Let's say I am on settings page and I clear all data. Now I press back to go back to profile page. Now I press back again (hardware back. gesture or back button) and go back to home page. Will the clear data change be reflected on the home screen ?

**Comment by subramanian42** [comment]
I have tested it both before and after adding the navigation bar, and it seems to be working as intended

**Comment by Spyy004** [comment]
Cool then.

**Review by Spyy004 — APPROVED** [review]
Thanks for the help and good change

**Pull request merged**
